### ISSUE TITLE
Cria Analytics

### ISSUE THREAD

**Issue by brunopulis** [talmidim/talmidim.github.io#2]
Gerar e colocar código de acompanhamento na página.

**Comment by gabrielazevedo** [comment]
Código do Google Analytics gerado e implementado no footer do projeto. @brunopulis

**Comment by brunopulis** [comment]
@gabrielazevedo Me dá permissão nele no dashboard do GA :+1:

**Comment by gabrielazevedo** [comment]
@brunopulis Adicionado. Verifique por favor

**Comment by brunopulis** [comment]
Certinho @gabrielazevedo  :)
