### ISSUE TITLE
Sessão de autores

### ISSUE THREAD

**Issue by brunopulis** [talmidim/talmidim.github.io#5]
Estou pensando em retirar a sessão de Autores.
Porque existem pessoas que vão querer o anônimato, como é o caso de um missionário amigo meu. 

E poderiamos ter N autores e criar uma descrição pra cada um acho que é insustentável. 

O que vocês acham @gabrielazevedo @rodrigoantinarelli  @JhonnyCosta  ?

**Comment by JhonnyCosta** [comment]
Bom dia, 

Também acho que é insustentável se for muitos autores. Se a sua idéia é retirar esta opção pensando nas pessoas que não querem se identificar, as que querem deveram colocar apenas seu nome no final do texto ou persar em algo ( hiperlink ) que leve o leitor a conhecer mais sobre aquele autor.

Atenciosamente.

**Comment by brunopulis** [comment]
@JhonnyCosta Show, fazer isso é tranquilo demais. :+1:

**Comment by brunopulis** [comment]
@JhonnyCosta @gabrielazevedo @rodrigoantinarelli Conversei com o @gabrielazevedo e decidimos retirar essa página, visto que algumas pessoas não queriam serem incluídas na sessão de Autores.

**Comment by rodrigoantinarelli** [comment]
:+1: GG
